name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop vidcruit || true
            docker rm vidcruit || true
            cd ~/vidcruit || git clone https://github.com/sohamsk13/Vidcruit.git vidcruit && cd vidcruit
            git pull origin main
            docker build -t vidcruit .
            docker run -d -p 80:3000 --name vidcruit vidcruit
          EOF
